[tool.poetry]
name = "http_forms_cows"
version = "0.1.0"
description = ""
authors = ["Janelle Kuhns <j3ckuhns@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.0.6"
cowsay = "^2.0.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
