# Generated by Django 3.0.6 on 2020-05-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CowsayTextInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cowsay_input', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CowsayTextOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cowsay_output', models.TextField()),
            ],
        ),
    ]
